{% set version = "13.1" %}

package:
  name: websockets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/websockets/websockets-{{ version }}.tar.gz
  sha256: a3b3366087c1bc0a2795111edcadddb8b3b59509d5db5d7ea3fdd69f954a8878

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  skip: true  # [py<37]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
  host:
    - python
    - setuptools
    - pip
  run:
    - python

test:
  imports:
    - websockets
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://websockets.readthedocs.io/en/stable/index.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for developing WebSocket servers and clients in Python.
  description: |
    websockets is a library for developing WebSocket servers and clients in
    Python. It implements RFC 6455 with a focus on correctness and simplicity.
    It passes the Autobahn Testsuite. Built on top of asyncio, Python's
    standard asynchronous I/O framework, it provides a straightforward API
    based on coroutines, making it easy to write highly concurrent
    applications.
  doc_url: https://websockets.readthedocs.io/en/stable/index.html
  dev_url: https://github.com/aaugustin/websockets

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
