{% set version = "9.0" %}

package:
  name: websockets
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/w/websockets/websockets-{{ version }}.tar.gz
  sha256: d865b206b43c9a27f1230d29708e498b0ae23a20e03b7718a653cb9e9a1c5969

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  skip: true  # [py<34]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - websockets

about:
  home: https://websockets.readthedocs.io/en/stable/index.html
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary: A library for developing WebSocket servers and clients in Python.
  description: |
    websockets is a library for developing WebSocket servers and clients in
    Python. It implements RFC 6455 with a focus on correctness and simplicity.
    It passes the Autobahn Testsuite. Built on top of asyncio, Python's
    standard asynchronous I/O framework, it provides a straightforward API
    based on coroutines, making it easy to write highly concurrent
    applications.
  doc_url: https://websockets.readthedocs.io/en/stable/index.html
  dev_url: https://github.com/aaugustin/websockets

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
