# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "17.0"
  python_min: "3.11"

package:
  name: websockets
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/w/websockets/websockets-${{ version }}.tar.gz
    sha256: 6bbe83c4ef52a7533d2d8c6a3512b93722fd0db6bc6bc638d45edd49ef201444
    target_directory: dist
  - url: https://github.com/python-websockets/websockets/archive/refs/tags/${{ version }}.tar.gz
    sha256: d01117def2bf1415adb44da34f08fc0ce217d76ce88177a307dbb31525de61c7
    target_directory: src

build:
  number: 0
  skip: match(python, "<" ~ python_min)
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

tests:
  - python:
      imports: websockets
      pip_check: true
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - pytest-cov
        - trio
        - werkzeug
    script:
      file: run_test.py

about:
  license: BSD-3-Clause
  license_file: dist/LICENSE
  summary: A library for developing WebSocket servers and clients in Python.
  description: |
    websockets is a library for developing WebSocket servers and clients in
    Python. It implements RFC 6455 with a focus on correctness and simplicity.
    It passes the Autobahn Testsuite. Built on top of asyncio, Python's
    standard asynchronous I/O framework, it provides a straightforward API
    based on coroutines, making it easy to write highly concurrent
    applications.
  homepage: https://pypi.org/project/websockets
  repository: https://github.com/python-websockets/websockets
  documentation: https://websockets.readthedocs.io

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
    - bollwyvl
