# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: "16.1.1"

package:
  name: websockets
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/w/websockets/websockets-${{ version }}.tar.gz
    sha256: db234eda965dcce15df96bb9709f587cd87d4d52aaf0e80e2f34ec04c7670c57
    target_directory: dist
  - url: https://github.com/python-websockets/websockets/archive/refs/tags/${{ version }}.tar.gz
    sha256: 2ab963cba7902071e9319914e673654e63b4b877f12950a3aa02eb7ccda7b701
    target_directory: src

build:
  number: 0
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

tests:
  - python:
      imports: websockets
      pip_check: true
  - files:
      source:
        - src/tests/
    requirements:
      run:
        - pytest-cov
        - werkzeug
    script:
      file: run_test.py

about:
  license: BSD-3-Clause
  license_file: dist/LICENSE
  summary: A library for developing WebSocket servers and clients in Python.
  description: |
    websockets is a library for developing WebSocket servers and clients in
    Python. It implements RFC 6455 with a focus on correctness and simplicity.
    It passes the Autobahn Testsuite. Built on top of asyncio, Python's
    standard asynchronous I/O framework, it provides a straightforward API
    based on coroutines, making it easy to write highly concurrent
    applications.
  homepage: https://pypi.org/project/websockets
  repository: https://github.com/python-websockets/websockets
  documentation: https://websockets.readthedocs.io

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
    - bollwyvl
