# yaml-language-server: $schema=https://raw.githubusercontent.com/prefix-dev/recipe-format/main/schema.json
schema_version: 1

context:
  version: 11.0.3

package:
  name: websockets
  version: ${{ version }}

source:
  - url: https://pypi.org/packages/source/w/websockets/websockets-${{ version }}.tar.gz
    sha256: 88fc51d9a26b10fc331be344f1781224a375b78488fc343620184e95a4b27016
    target_directory: dist
  - url: https://github.com/python-websockets/websockets/archive/refs/tags/${{ version }}.tar.gz
    sha256: e412f6480c9bf8d5a58cb746a4d20df391a19017b6d2c39b136d84b0be8309c9
    target_directory: src

build:
  number: 2
  script:
    - cd dist
    - ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation --disable-pip-version-check

requirements:
  build:
    - ${{ compiler("c") }}
    - ${{ stdlib("c") }}
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
  host:
    - pip
    - python
    - setuptools
  run:
    - python

tests:
  - python:
      imports: websockets
      pip_check: true
  - files:
      source:
        - src/tests/
      recipe:
        - run_test.py
    requirements:
      run:
        - pytest-cov
        - werkzeug
    script:
      - python run_test.py

about:
  license: BSD-3-Clause
  license_file: dist/LICENSE
  summary: A library for developing WebSocket servers and clients in Python.
  description: |
    websockets is a library for developing WebSocket servers and clients in
    Python. It implements RFC 6455 with a focus on correctness and simplicity.
    It passes the Autobahn Testsuite. Built on top of asyncio, Python's
    standard asynchronous I/O framework, it provides a straightforward API
    based on coroutines, making it easy to write highly concurrent
    applications.
  homepage: https://websockets.readthedocs.io/en/stable/index.html
  repository: https://github.com/aaugustin/websockets
  documentation: https://websockets.readthedocs.io/en/stable/index.html

extra:
  recipe-maintainers:
    - scopatz
    - ocefpaf
    - bollwyvl
